function loadScriptContent(container) {
  const cities = [
{ name:"Abatiá", borderingCities: ["Bandeirantes","Cornélio Procópio","Jundiaí do Sul","Ribeirão do Pinhal","Santa Amélia","Santo Antônio da Platina"] },
{ name:"Adrianópolis", borderingCities: ["Barra do Turvo (SP)","Bocaiúva do Sul","Cerro Azul","Iporanga (SP)","Itaóca (SP)","Ribeira (SP)","Tunas do Paraná"] },
{ name:"Agudos do Sul", borderingCities: ["Campo Alegre (SC)","Mandirituba","Piên","Quitandinha","Tijucas do Sul"] },
{ name:"Almirante Tamandaré", borderingCities: ["Campo Magro","Colombo","Curitiba","Itaperuçu","Rio Branco do Sul"] },
{ name:"Altamira do Paraná", borderingCities: ["Campina da Lagoa","Diamante do Sul","Guaraniaçu","Laranjal","Nova Cantu"] },
{ name:"Alto Paraíso", borderingCities: ["Esperança Nova","Icaraíma","Itaquiraí (MS)","Naviraí (MS)","São Jorge do Patrocínio","Umuarama","Xambrê"] },
{ name:"Alto Paraná", borderingCities: ["Cruzeiro do Sul","Nova Esperança","Paranavaí","São João do Caiuá","Tamboara"] },
{ name:"Alto Piquiri", borderingCities: ["Assis Chateaubriand","Brasilândia do Sul","Cafezal do Sul","Formosa do Oeste","Mariluz","Perobal"] },
{ name:"Altônia", borderingCities: ["Eldorado (MS)","Guaíra","Iporã","Mundo Novo (MS)","Pérola","São Jorge do Patrocínio","Terra Roxa"] },
{ name:"Alvorada do Sul", borderingCities: ["Bela Vista do Paraíso","Florestópolis","Iepê (SP)","Nantes (SP)","Porecatu","Primeiro de Maio","Taciba(SP)"] },
{ name:"Amaporã", borderingCities: ["Cidade Gaúcha","Guairaçá","Guaporema","Mirador","Paranavaí","Planaltina do Paraná"] },
{ name:"Ampére", borderingCities: ["Bela Vista da Caroba","Francisco Beltrão","Manfrinópolis","Nova esperança do Sudoeste","Pérola d'Oeste","Pinhal de São Bento","Planalto","Pranchita","Realiza","Santa Izabel do Oeste","Santo Antônio do Sudoeste"] },
{ name:"Anahy", borderingCities: ["Corbélia","Iguatu","Ubiratã"] },
{ name:"Andirá", borderingCities: ["Bandeirantes","Barra do Jacaré","Cambará","Itambaracá","Palmital (SP)"] },
{ name:"Ângulo", borderingCities: ["Flórida","Iguaraçu","Mandaguaçu","Maringá","Santa Fé"] },
{ name:"Antonina", borderingCities: ["Campina Grande do Sul","Guaraqueçaba","Morretes","Paranaguá"] },
{ name:"Antônio Olinto", borderingCities: ["Lapa","Mafra (SC)","São João do Triunfo","São Mateus do Sul","Três Barras (SC)"] },
{ name:"Apucarana", borderingCities: ["Arapongas","Califórnia","Cambira","Londrina","Mandaguari","Marilândia do Sul","Novo Itacolomi","Rio Bom","Sabáudia"] },
{ name:"Arapongas", borderingCities: ["Apucarana","Londrina","Rolândia","Sabáudia"] },
{ name:"Arapoti", borderingCities: ["Ibaiti","Jaguariaíva","Pinhalão","Piraí do Sul","São José da Boa Vista","Tomazina","Ventania","Wenceslau Braz"] },
{ name:"Arapuã", borderingCities: ["Ivaiporã","Jardim Alegre","Manoel Ribas","Nova Tebas"] },
{ name:"Araruna", borderingCities: ["Campo Mourão","Cianorte","Farol","Jussara","Peabiru","Terra Boa","Tuneiras do Oeste"] },
{ name:"Araucária", borderingCities: ["Balsa Nova","Campo Largo","Contenda","Curitiba","Fazenda Rio Grande","Mandirituba","Quitandinha"] },
{ name:"Ariranha do Ivaí", borderingCities: ["Cândido de Abreu","Ivaiporã","Manoel Ribas","Rio Branco do Ivaí"] },
{ name:"Assaí", borderingCities: ["Ibiporã","Jataizinho","Londrina","Nova América da Colina","Santa Cecília do Pavão","São Jerônimo da Serra","São Sebastião da Amoreira","Uraí"] },
{ name:"Assis Chateaubriand", borderingCities: ["Alto Piquiri","Brasilândia do Sul","Formosa do Oeste","Iporã","Jesuítas","Maripá","Nova Aurora","Palotina","Toledo","Tupãssi"] },
{ name:"Astorga", borderingCities: ["Iguaraçu","Jaguapitã","Mandaguari","Marialva","Maringá","Munhoz de Melo","Pitangueiras","Sabáudia"] },
{ name:"Atalaia", borderingCities: ["Flórida","Lobato","Mandaguaçu","Nova Esperança","Presidente Castelo Branco","Uniflor"] },
{ name:"Balsa Nova", borderingCities: ["Araucária","Campo Largo","Contenda","Lapa","Palmeira","Porto Amazonas"] },
{ name:"Bandeirantes", borderingCities: ["Abatiá","Andirá","Barra do Jacaré","Cornélio Procópio","Itambaracá","Santa Amélia","Santa Mariana","Santo Antônio da Platina"] },
{ name:"Barbosa Ferraz", borderingCities: ["Corumbataí do Sul","Fênix","Godoy Moreira","Iretama","Luiziana","Peabiru","São João do Ivaí"] },
{ name:"Barra do Jacaré", borderingCities: ["Andirá","Bandeirantes","Cambará","Jacarezinho","Santo Antônio da Platina"] },
{ name:"Barracão", borderingCities: ["Bom Jesus do Sul","Dionísio Cerqueira (SC)","Flor da Serra do Sul"] },
{ name:"Bela Vista da Caroba", borderingCities: ["Ampére","Pérola d'Oeste","Pranchita"] },
{ name:"Bela Vista do Paraíso", borderingCities: ["Alvorada do Sul","Cambé","Florestópolis","Prado Ferreira","Primeiro de Maio","Sertanópolis"] },
{ name:"Bituruna", borderingCities: ["Coronel Domingos Soares","Cruz Machado","General Carneiro","Palmas","Pinhão","Porto Vitória","União da Vitória"] },
{ name:"Boa Esperança", borderingCities: ["Farol","Janiópolis","Juranda","Mamborê"] },
{ name:"Boa Esperança do Iguaçu", borderingCities: ["Cruzeiro do Iguaçu","Dois Vizinhos","Nova Prata do Iguaçu","Salto do Lontra","Três Barras do Paraná"] },
{ name:"Boa Ventura de São Roque", borderingCities: ["Cândido de Abreu","Pitanga","Santa Maria do Oeste","Turvo"] },
{ name:"Boa Vista da Aparecida", borderingCities: ["Capitão Leônidas Marques","Cascavel","Nova Prata do Iguaçu","Santa Lúcia","Três Barras do Paraná"] },
{ name:"Bocaiúva do Sul", borderingCities: ["Cerro Azul"," Colombo","Adrianópolis","Barra do Turvo(SP)","Campina Grande do Sul","Rio Branco do Sul","Tunas do Paraná"] },
{ name:"Bom Jesus do Sul", borderingCities: ["Barracão","Flor da Serra do Sul","Salgado Filho","Santo Antônio do Sudoeste"] },
{ name:"Bom Sucesso", borderingCities: ["Itambé","Jandaia do Sul","Mandaguari","Marialva","Marumbi","São Pedro do Ivaí"] },
{ name:"Bom Sucesso do Sul", borderingCities: ["Francisco Beltrão","Itapejara d'Oeste","Pato Branco","Renascença","Vitorino"] },
{ name:"Borrazópolis", borderingCities: ["Cruzmaltina","Faxinal","Kaloré","Lidianópolis","Lunardelli","Novo Itacolomi","Rio Bom","São João do Ivaí"] },
{ name:"Braganey", borderingCities: ["Campina da Lagoa","Campo Bonito","Cascavel","Corbélia","Iguatu","Ubiratã"] },
{ name:"Brasilândia do Sul", borderingCities: ["Alto Piquiri","Assis Chateaubriand","Cafezal do Sul","Iporã","Iporã"] },
{ name:"Cafeara", borderingCities: ["Centenário do Sul","Guaraci","Lupionópolis","Nossa Senhora das Graças","Santo Inácio"] },
{ name:"Cafelândia", borderingCities: ["Cascavel","Corbélia","Nova Aurora","Tupãssi"] },
{ name:"Cafezal do Sul", borderingCities: ["Alto Piquiri","Brasilândia do Sul","Iporã","Perobal","Pérola","Umuarama","Xambrê"] },
{ name:"Califórnia", borderingCities: ["Apucarana","Marilândia do Sul"] },
{ name:"Cambará", borderingCities: ["Andirá","Barra do Jacaré","Ibirarema (SP)","Jacarezinho","Palmital(SP)","Salto Grande (SP)"] },
{ name:"Cambé", borderingCities: ["Bela Vista do Paraíso","Jaguapitã","Londrina","Prado Ferreira","Rolândia","Sertanópolis"] },
{ name:"Cambira", borderingCities: ["Apucarana","Jandaia do Sul","Mandaguari","Marumbi","Novo Itacolomi"] },
{ name:"Campina da Lagoa", borderingCities: ["Altamira do Paraná","Braganey","Campo Bonito","Guaraniaçu","Juranda","Mamborê","Nova Cantu","Ubiratã"] },
{ name:"Campina do Simão", borderingCities: ["Goioxim","Guarapuava","Santa Maria do Oeste","Turvo"] },
{ name:"Campina Grande do Sul", borderingCities: ["Antonina","Barra do Turvo (SP)","Bocaiúva do Sul","Colombo","Guaraqueçaba","Morretes","Quatro Barras"] },
{ name:"Campo Bonito", borderingCities: ["Braganey","Campina da Lagoa","Cascavel","Catanduvas","Guaraniaçu","Ibema"] },
{ name:"Campo do Tenente", borderingCities: ["Lapa","Piên","Quitandinha","Rio Negro"] },
{ name:"Campo Largo", borderingCities: ["Araucária","Balsa Nova","Campo Magro","Castro","Curitiba","Itaperuçu","Palmeira","Ponta Grossa"] },
{ name:"Campo Magro", borderingCities: ["Almirante Tamandaré","Campo Largo","Curitiba","Itaperuçu"] },
{ name:"Campo Mourão", borderingCities: ["Araruna","Barbosa Ferraz","Corumbataí do Sul","Farol","Luiziana","Mamborê","Peabiru"] },
{ name:"Cândido de Abreu", borderingCities: ["Ariranha do Ivaí","Boa Ventura de São Roque","Ivaí","Manoel Ribas","Pitanga","Prudentópolis","Reserva","Rio Branco do Ivaí","Rosário do Ivaí","Turvo"] },
{ name:"Candói", borderingCities: ["Cantagalo","Chopinzinho","Foz do Jordão","Guarapuava","Pinhão","Porto Barreiro","Virmond"] },
{ name:"Cantagalo", borderingCities: ["Candói","Goioxim","Guarapuava","Laranjeiras do Sul","Marquinho","Virmond"] },
{ name:"Capanema", borderingCities: ["Capitão Leônidas Marques","Céu Azul","Matelândia","Planalto","Realeza","Serranópolis do Iguaçu"] },
{ name:"Capitão Leônidas Marques", borderingCities: ["Boa Vista da Aparecida","Capanema","Céu Azul","Lindoeste","Nova Prata do Iguaçu","Realeza","Santa Lúcia"] },
{ name:"Carambeí", borderingCities: ["Castro","Ponta Grossa","Tibagi"] },
{ name:"Carlópolis", borderingCities: ["Barão de Antonina(SP)","Fartura(SP)","Joaquim Távora","Ribeirão Claro","Salto do Itararé","Siqueira Campos"] },
{ name:"Cascavel", borderingCities: ["Boa Vista da Aparecida","Braganey","Cafelândia","Campo Bonito","Catanduvas","Corbélia","Ibema","Lindoeste","Santa Tereza do Oeste","Toledo","Três Barras do Paraná","Tupãssi"] },
{ name:"Castro", borderingCities: ["Campo Largo","Carambeí","Cerro Azul","Doutor Ulysses","Itaperuçu","Piraí do Sul","Ponta Grossa","Rio Branco do Sul","Tibagi"] },
{ name:"Catanduvas", borderingCities: ["Campo Bonito","Cascavel","Guaraniaçu","Ibema","Quedas do Iguaçu","Três Barras do Paraná"] },
{ name:"Centenário do Sul", borderingCities: ["Cafeara","Florestópolis","Guaraci","Jaguapitã","Lupionópolis","Miraselva","Narandiba (SP)","Porecatu"] },
{ name:"Cerro Azul", borderingCities: ["Adrianópolis","Bocaiúva do Sul","Castro","Doutor Ulysses","Itapirapuã Paulista(SP)","Ribeira (SP)","Rio Branco do Sul","Tunas do Paraná"] },
{ name:"Céu Azul", borderingCities: ["Capanema","Capitão Leônidas Marques","Lindoeste","Matelândia","Santa Tereza do Oeste","São Pedro do Iguaçu","Vera Cruz do Oeste"] },
{ name:"Chopinzinho", borderingCities: ["Candói","Coronel Vivida","Foz do Jordão","Mangueirinha","Porto Barreiro","Rio Bonito do Iguaçu","São João","Saudade do Iguaçu","Sulina"] },
{ name:"Cianorte", borderingCities: ["Araruna","Indianopolis","Jussara","São Tomé","Tapejara","Tuneiras do Oeste"] },
{ name:"Cidade Gaúcha", borderingCities: ["Amaporã","Guaporema","Nova Olímpia","Planaltina do Paraná","Rondon","Tapejara","Tapira"] },
{ name:"Clevelândia", borderingCities: ["Abelardo Luz (SC)","Coronel Domingos Soares","Honório Serpa","Mangueirinha","Mariópolis","Palmas","Pato Branco","São Domingos (SC)"] },
{ name:"Colombo", borderingCities: ["Almirante Tamandaré","Bocaiúva do Sul","Campina Grande do Sul","Curitiba","Pinhais","Quatro Barras","Rio Branco do Sul"] },
{ name:"Colorado", borderingCities: ["Itaguajé","Lobato","Nossa Senhora das Graças","Paranacity","Paranapoema","Santa Fé","Santa Inês","Santo Inácio"] },
{ name:"Congonhinhas", borderingCities: ["Ibaiti","Nova Fátima","Ribeirão do Pinhal","Santo Antônio do Paraíso","São Jerônimo da Serra","Sapopema"] },
{ name:"Conselheiro Mairinck", borderingCities: ["Guapirama","Jaboti","Japira","Jundiaí do Sul","Tomazina"] },
{ name:"Contenda", borderingCities: ["Araucária","Balsa Nova","Lapa","Quitandinha"] },
{ name:"Corbélia", borderingCities: ["Anahy","Braganey","Cafelândia","Cascavel","Iguatu","Nova Aurora","Ubiratã"] },
{ name:"Cornélio Procópio", borderingCities: ["Bandeirantes","Leópolis","Nova América da Colina","Nova Fátima","Ribeirão do Pinhal","Santa Amélia","Santa Mariana","Uraí"] },
{ name:"Coronel Domingos Soares", borderingCities: ["Bituruna","Clevelândia.","Mangueirinha","Palmas","Pinhão","Reserva do Iguaçu"] },
{ name:"Coronel Vivida", borderingCities: ["Chopinzinho","Honório Serpa","Itapejara d'Oeste","Mangueirinha","Pato Branco","São João"] },
{ name:"Corumbataí do Sul", borderingCities: ["Barbosa Ferraz","Campo Mourão","Peabiru"] },
{ name:"Cruz Machado", borderingCities: ["Bituruna","Inácio Martins","Mallet","Pinhão","Rio Azul","União da Vitória"] },
{ name:"Cruzeiro do Iguaçu", borderingCities: ["Boa Esperança do Iguaçu","Dois Vizinhos","Quedas do Iguaçu","São Jorge d'Oeste","Três Barras do Paraná"] },
{ name:"Cruzeiro do Oeste", borderingCities: ["Maria Helena","Mariluz","Moreira Sales","Nova Olímpia","Tapejara","Tuneiras do Oeste","Umuarama"] },
{ name:"Cruzeiro do Sul", borderingCities: ["Alto Paraná","Lobato","Nova Esperança","Paranacity","São João do Caiuá","Uniflor"] },
{ name:"Cruzmaltina", borderingCities: ["Borrazópolis","Faxinal","Grandes Rios","Lidianópolis"] },
{ name:"Curitiba", borderingCities: ["Almirante Tamandaré","Araucária","Campo Largo","Campo Magro","Colombo","Fazenda Rio Grande","Pinhais","São José dos Pinhais"] },
{ name:"Curiúva", borderingCities: ["Figueira","Ibaiti","Ortigueira","Sapopema","Telêmaco Borba","Ventania"] },
{ name:"Diamante do Norte", borderingCities: ["Itaúna do Sul","Nova Londrina","Rosana(SP)","Terra Rica"] },
{ name:"Diamante do Sul", borderingCities: ["Altamira do Paraná","Guaraniaçu","Laranjal","Nova Laranjeiras"] },
{ name:"Diamante D'Oeste", borderingCities: ["Matelândia","Missal","Ramilândia","Santa Helena","São José das Palmeiras","São Pedro do Iguaçu","Vera Cruz do Oeste"] },
{ name:"Dois Vizinhos", borderingCities: ["Boa Esperança do Iguaçu","Cruzeiro do Iguaçu","Enéas Marques","Salto do Lontra","São Jorge d'Oeste","Verê"] },
{ name:"Douradina", borderingCities: ["Ivaté","Maria Helena","Santa Cruz de Monte Castelo","Santa Isabel do Ivaí","Tapira","Umuarama"] },
{ name:"Doutor Camargo", borderingCities: ["Ivatuba","Ourizona","Paiçandu","Terra Boa"] },
{ name:"Doutor Ulysses", borderingCities: ["Barra do Chapéu(SP)","Castro","Cerro Azul","Itapirapuã Paulista (SP)","Jaguariaíva","Piraí do Sul","Sengés"] },
{ name:"Enéas Marques", borderingCities: ["Dois Vizinhos","Francisco Beltrão","Nova Esperança do Sudoeste","Salto do Lontra","Verê"] },
{ name:"Engenheiro Beltrão", borderingCities: ["Floresta","Itambé","Ivatuba","Peabiru","Quinta do Sol","Terra Boa"] },
{ name:"Entre Rios do Oeste", borderingCities: ["Marechal Cândido Rondon","Pato Bragado","Santa Helena","São José das Palmeiras"] },
{ name:"Esperança Nova", borderingCities: ["Alto Paraíso","Pérola","São Jorge do Patrocínio","Xambrê"] },
{ name:"Espigão Alto do Iguaçu", borderingCities: ["Guaraniaçu","Nova Laranjeiras","Quedas do Iguaçu","Rio Bonito do Iguaçu"] },
{ name:"Farol", borderingCities: ["Araruna","Boa Esperança","Campo Mourão","Janiópolis","Mamborê","Tuneiras do Oeste"] },
{ name:"Faxinal", borderingCities: ["Borrazópolis","Cruzmaltina","Grandes Rios","Marilândia do Sul","Mauá da Serra","Ortigueira","Rio Bom"] },
{ name:"Fazenda Rio Grande", borderingCities: ["Araucária","Curitiba","Mandirituba","São José dos Pinhais"] },
{ name:"Fênix", borderingCities: ["Barbosa Ferraz","Itambé","Peabiru","Quinta do Sol","São João do Ivaí","São Pedro do Ivaí"] },
{ name:"Fernandes Pinheiro", borderingCities: ["Irati","Imbituva","Rebouças","São João do Triunfo","Teixeira Soares"] },
{ name:"Figueira", borderingCities: ["Curiúva","Ibaiti","Sapopema"] },
{ name:"Flor da Serra do Sul", borderingCities: ["Manfrinópolis","Barracão","Bom Jesus do Sul","Dionísio Cerqueira(SC)","Francisco Beltrão","Marmeleiro","Palma Sola(SC)","Salgado Filho"] },
{ name:"Floraí", borderingCities: ["Nova Esperança","Presidente Castelo Branco","São Carlos do Ivaí","São Jorge do Ivaí","Tamboara"] },
{ name:"Floresta", borderingCities: ["Engenheiro Beltrão","Itambé","Ivatuba","Marialva","Maringá"] },
{ name:"Florestópolis", borderingCities: ["Alvorada do Sul","Bela Vista do Paraíso","Centenário do Sul","Miraselva","Porecatu","Prado Ferreira"] },
{ name:"Flórida", borderingCities: ["Ângulo","Atalaia","Lobato","Mandaguaçu","Santa Fé"] },
{ name:"Formosa do Oeste", borderingCities: ["Alto Piquiri","Assis Chateaubriand","Goioerê","Iracema do Oeste","Jesuítas","Mariluz","Nova Aurora","Quarto Centenário"] },
{ name:"Foz do Iguaçu", borderingCities: ["Itaipulândia","Santa Terezinha de Itaipu","São Miguel do Iguaçu"] },
{ name:"Foz do Jordão", borderingCities: ["Candói","Chopinzinho","Mangueirinha","Pinhão","Reserva do Iguaçu"] },
{ name:"Francisco Alves", borderingCities: ["Iporã","Palotina","Terra Roxa"] },
{ name:"Francisco Beltrão", borderingCities: ["Ampére","Bom Sucesso do Sul","Enéas Marques","Flor da Serra do Sul","Itapejara d'Oeste","Manfrinópolis","Marmeleiro","Nova Esperança do Sudoeste","Renascença","Verê"] },
{ name:"General Carneiro", borderingCities: ["Água Doce (SC)","Bituruna","Caçador (SC)","Calmon(SC)","Matos Costa(SC)","Palmas","Porto União(SC)","Porto Vitória"] },
{ name:"Godoy Moreira", borderingCities: ["Barbosa Ferraz","Iretama","Jardim Alegre","Lunardelli","São João do Ivaí"] },
{ name:"Goioerê", borderingCities: ["Formosa do Oeste","Janiópolis","Mariluz","Moreira Sales","Quarto Centenário","Rancho Alegre d'Oeste"] },
{ name:"Goioxim", borderingCities: ["Campina do Simão","Cantagalo","Guarapuava","Marquinho","Palmital","Santa Maria do Oeste"] },
{ name:"Grandes Rios", borderingCities: ["Cruzmaltina","Faxinal","Ivaiporã","Jardim Alegre","Lidianópolis","Ortigueira","Rio Branco do Ivaí","Rosário do Ivaí"] },
{ name:"Guaíra", borderingCities: ["Altônia","Mercedes","Mundo Novo (MS)","Terra Roxa"] },
{ name:"Guairaçá", borderingCities: ["Amaporã","Loanda","Nova Londrina","Paranavaí","Planaltina do Paraná","Terra Rica"] },
{ name:"Guamiranga", borderingCities: ["Imbituva","Ivaí","Prudentópolis"] },
{ name:"Guapirama", borderingCities: ["Conselheiro Mairinck","Joaquim Távora","Jundiaí do Sul","Quatiguá","Santo Antônio da Platina","Tomazina"] },
{ name:"Guaporema", borderingCities: ["Amaporã","Cidade Gaúcha","Mirador","Paraíso do Norte","Rondon"] },
{ name:"Guaraci", borderingCities: ["Cafeara","Centenário do Sul","Jaguapitã","Nossa Senhora das Graças","Santa Fé"] },
{ name:"Guaraniaçu", borderingCities: ["Quedas do Iguaçu","Altamira do Paraná","Campina da Lagoa","Campo Bonito","Catanduvas","Diamante do Sul","Espigão Alto do Iguaçu","Ibema","Nova Laranjeiras"] },
{ name:"Guarapuava", borderingCities: ["Campina do Simão","Candói","Cantagalo","Goioxim","Inácio Martins","Pinhão","Prudentópolis","Turvo"] },
{ name:"Guaraqueçaba", borderingCities: ["Antonina","Barra do Turvo (São Paulo).","Campina Grande do Sul","Cananéia (São Paulo)","Paranaguá"] },
{ name:"Guaratuba", borderingCities: ["Garuva (SC)","Itapoá (SC)","Matinhos","Morretes","Paranaguá","São José dos Pinhais","Tijucas do Sul"] },
{ name:"Honório Serpa", borderingCities: ["Clevelândia","Coronel Vivida","Mangueirinha","Pato Branco"] },
{ name:"Ibaiti", borderingCities: ["Arapoti","Congonhinhas","Curiúva","Figueira","Japira","Jundiaí do Sul","Pinhalão","Ribeirão do Pinhal","Sapopema","Ventania"] },
{ name:"Ibema", borderingCities: ["Campo Bonito","Catanduvas","Guaraniaçu"] },
{ name:"Ibiporã", borderingCities: ["Assaí","Jataizinho","Londrina","Rancho Alegre","Sertanópolis"] },
{ name:"Icaraíma", borderingCities: ["Alto Paraíso","Ivaté","Naviraí (MS)","Querência do Norte","Umuarama"] },
{ name:"Iguaraçu", borderingCities: ["Ângulo","Astorga","Maringá","Munhoz de Melo","Santa Fé"] },
{ name:"Iguatu", borderingCities: ["Anahy","Braganey","Corbélia","Ubiratã"] },
{ name:"Imbaú", borderingCities: ["Ortigueira","Reserva","Telêmaco Borba","Tibagi"] },
{ name:"Imbituva", borderingCities: ["Fernandes Pinheiro","Guamiranga","Ipiranga","Irati","Ivaí","Prudentópolis","Teixeira Soares"] },
{ name:"Inácio Martins", borderingCities: ["Cruz Machado","Guarapuava","Irati","Pinhão","Prudentópolis","Rio Azul"] },
{ name:"Inajá", borderingCities: ["Paranacity","Paranapoema","Santo Antônio do Caiuá","São João do Caiuá","Teodoro Sampaio(SP)"] },
{ name:"Indianópolis", borderingCities: ["Cianorte","Japurá","Rondon","São Manoel do Paraná","São Tomé","Tapejara"] },
{ name:"Ipiranga", borderingCities: ["Imbituva","Ivaí","Ponta Grossa","Teixeira Soares","Tibagi"] },
{ name:"Iporã", borderingCities: ["Altônia","Assis Chateaubriand","Brasilândia do Sul","Cafezal do Sul","Francisco Alves","Palotina","Pérola","Terra Roxa"] },
{ name:"Iracema do Oeste", borderingCities: ["Formosa do Oeste","Jesuítas","Nova Aurora"] },
{ name:"Irati", borderingCities: ["Fernandes Pinheiro","Imbituva","Inácio Martins","Prudentópolis","Rebouças","Rio Azul"] },
{ name:"Iretama", borderingCities: ["Barbosa Ferraz","Godoy Moreira","Jardim Alegre","Luiziana","Nova Tebas","Roncador"] },
{ name:"Itaguajé", borderingCities: ["Colorado","Jardim Olinda","Paranapoema","Sandovalina(SP)","Santa Inês"] },
{ name:"Itaipulândia", borderingCities: ["Foz do Iguaçu","Medianeira","Missal","Santa Helena","São Miguel do Iguaçu"] },
{ name:"Itambaracá", borderingCities: ["Andirá","Bandeirantes","Cândido Mota(SP)","Palmital(SP)","Santa Mariana"] },
{ name:"Itambé", borderingCities: ["Bom Sucesso","Engenheiro Beltrão","Fênix","Floresta","Marialva","Quinta do Sol","São Pedro do Ivaí"] },
{ name:"Itapejara d'Oeste", borderingCities: ["Bom Sucesso do Sul","Coronel Vivida","Francisco Beltrão","Pato Branco","São João","Verê"] },
{ name:"Itaperuçu", borderingCities: ["Almirante Tamandaré","Campo Largo","Campo Magro","Castro","Cerro Azul","Rio Branco do Sul"] },
{ name:"Itaúna do Sul", borderingCities: ["Diamante do Norte","Nova Londrina","Terra Rica"] },
{ name:"Ivaí", borderingCities: ["Cândido de Abreu","Guamiranga","Imbituva","Ipiranga","Prudentópolis","Reserva","Tibagi"] },
{ name:"Ivaiporã", borderingCities: ["Arapuã"," Ariranha do Ivaí"," Manoel Ribas"," Rio Branco do Ivaí","Grandes Rios","Jardim Alegre"] },
{ name:"Ivaté", borderingCities: ["Douradina","Icaraíma","Querência do Norte","Santa Cruz de Monte Castelo","Umuarama"] },
{ name:"Ivatuba", borderingCities: ["Doutor Camargo","Engenheiro Beltrão","Floresta","Terra Boa"] },
{ name:"Jaboti", borderingCities: ["Conselheiro Mairinck","Japira","Pinhalão","Tomazina"] },
{ name:"Jacarezinho", borderingCities: ["Barra do Jacaré","Cambará","Canitar(SP)","Chavantes(SP)","Joaquim Távora","Ourinhos(SP)","Ribeirão Claro","Santo Antônio da Platina"] },
{ name:"Jaguapitã", borderingCities: ["Astorga","Cambé","Centenário do Sul","Guaraci","Miraselva","Munhoz de Melo","Pitangueiras","Prado Ferreira","Rolândia","Santa Fé"] },
{ name:"Jaguariaíva", borderingCities: ["Arapoti","Doutor Ulysses","Piraí do Sul","São José da Boa Vista","Sengés"] },
{ name:"Jandaia do Sul", borderingCities: ["Bom Sucesso","Cambira","Mandaguari","Marumbi"] },
{ name:"Janiópolis", borderingCities: ["Tuneira do Oeste","Boa Esperança","Farol","Goioerê","Moreira Sales","Rancho Alegre d'Oeste"] },
{ name:"Japira", borderingCities: ["Conselheiro Mairinck","Ibaiti","Jaboti","Jundiaí do Sul","Pinhalão"] },
{ name:"Japurá", borderingCities: ["Indianópolis","São Carlos do Ivaí","São Manoel do Paraná","São Tomé"] },
{ name:"Jardim Alegre", borderingCities: ["Arapuã","Godoy Moreira","Grandes Rios","Iretama","Ivaiporã","Lidianópolis","Lunardelli","Nova Tebas"] },
{ name:"Jardim Olinda", borderingCities: ["Itaguajé","Mirante do Paranapanema (SP)","Paranapoema","Sandovalina (SP)","Teodoro Sampaio (SP)"] },
{ name:"Jataizinho", borderingCities: ["Assaí","Ibiporã","Rancho Alegre","Uraí"] },
{ name:"Jesuítas", borderingCities: ["Assis Chateaubriand","Formosa do Oeste","Iracema do Oeste","Nova Aurora"] },
{ name:"Joaquim Távora", borderingCities: ["Carlópolis","Guapirama","Jacarezinho","Quatiguá","Ribeirão Claro","Santo Antônio da Platina","Siqueira Campos"] },
{ name:"Jundiaí do Sul", borderingCities: ["Abatiá","Conselheiro Mairinck","Guapirama","Ibaiti","Japira","Ribeirão do Pinhal","Santo Antônio da Platina"] },
{ name:"Juranda", borderingCities: ["Boa Esperança","Campina da Lagoa","Mamborê","Rancho Alegre D'Oeste","Ubiratã"] },
{ name:"Jussara", borderingCities: ["Araruna","Cianorte","São Jorge do Ivaí","São Tomé","Terra Boa"] },
{ name:"Kaloré", borderingCities: ["Borrazópolis","Marumbi","Novo Itacolomi","São João do Ivaí","São Pedro do Ivaí"] },
{ name:"Lapa", borderingCities: ["Antônio Olinto","Balsa Nova","Campo do Tenente","Contenda","Mafra (SC)","Palmeira","Porto Amazonas","Quitandinha","Rio Negro","São João do Triunfo"] },
{ name:"Laranjal", borderingCities: ["Altamira do Paraná","Diamante do Sul","Nova Cantu","Nova Laranjeiras","Palmital"] },
{ name:"Laranjeiras do Sul", borderingCities: ["Marquinho","Nova Laranjeiras","Porto Barreiro","Rio Bonito do Iguaçu","Virmond"] },
{ name:"Leópolis", borderingCities: ["Cornélio Procópio","Florínia(SP)","Santa Mariana","Sertaneja","Uraí"] },
{ name:"Lidianópolis", borderingCities: ["Borrazópolis","Cruzmaltina","Grandes Rios","Jardim Alegre","Lunardelli"] },
{ name:"Lindoeste", borderingCities: ["Boa Vista da Aparecida","Capitão Leônidas Marques","Cascavel","Céu Azul","Santa Lúcia","Santa Tereza do Oeste"] },
{ name:"Loanda", borderingCities: ["Guairaçá","Marilena","Nova Londrina","Planaltina do Paraná","Porto Rico","Santa Cruz de Monte Castelo","Santa Isabel do Ivaí","Santa Mônica","São Pedro do Paraná"] },
{ name:"Lobato", borderingCities: ["Atalaia","Colorado","Cruzeiro do Sul","Flórida","Paranacity","Santa Fé","Uniflor"] },
{ name:"Londrina", borderingCities: ["Apucarana","Arapongas","Assaí","Cambé","Ibiporã","Marilândia do Sul","São Jerônimo da Serra","Sertanópolis","Tamarana"] },
{ name:"Luiziana", borderingCities: ["Barbosa Ferraz","Campo Mourão","Iretama","Mamborê","Roncador"] },
{ name:"Lunardelli", borderingCities: ["Borrazópolis","Godoy Moreira","Jardim Alegre","Lidianópolis","São João do Ivaí"] },
{ name:"Lupionópolis", borderingCities: ["Cafeara","Centenário do Sul","Pirapozinho(SP)","Santo Inácio"] },
{ name:"Mallet", borderingCities: ["Cruz Machado","Paulo Frontin","Rio Azul","São Mateus do Sul","União da Vitória"] },
{ name:"Mamborê", borderingCities: ["Boa Esperança","Campina da Lagoa","Campo Mourão","Farol","Juranda","Luiziana","Nova Cantu"] },
{ name:"Mandaguaçu", borderingCities: ["Ângulo","Atalaia","Flórida","Maringá","Ourizona","Paiçandu","Presidente Castelo Branco"] },
{ name:"Mandaguari", borderingCities: ["Apucarana","Astorga","Bom Sucesso","Cambira","Jandaia do Sul","Marialva","Sabáudia"] },
{ name:"Mandirituba", borderingCities: ["Agudos do Sul","Araucária","Fazenda Rio Grande","Quitandinha","São José dos Pinhais","Tijucas do Sul"] },
{ name:"Manfrinópolis", borderingCities: ["Ampére","Flor da Serra do Sul","Francisco Beltrão","Pinhal de São Bento","Salgado Filho"] },
{ name:"Mangueirinha", borderingCities: ["Chopinzinho","Clevelândia","Coronel Domingos Soares","Coronel Vivida","Foz do Jordão","Honório Serpa","Reserva do Iguaçu"] },
{ name:"Manoel Ribas", borderingCities: ["Arapuã","Ariranha do Ivaí","Cândido de Abreu","Ivaiporã","Nova Tebas","Pitanga"] },
{ name:"Marechal Cândido Rondon", borderingCities: ["Entre Rios do Oeste","Mercedes","Nova Santa Rosa","Ouro Verde do Oeste","Pato Bragado","Quatro Pontes","Toledo"] },
{ name:"Maria Helena", borderingCities: ["Cruzeiro do Oeste","Douradina.","Nova Olímpia","Tapira","Umuarama"] },
{ name:"Marialva", borderingCities: ["Astorga","Bom Sucesso","Floresta","Itambé","Mandaguari","Maringá","Sarandi"] },
{ name:"Marilândia do Sul", borderingCities: ["Apucarana","Califórnia","Faxinal","Londrina","Mauá da Serra","Rio Bom","Tamarana"] },
{ name:"Marilena", borderingCities: ["Batayporã(MS)","Loanda","Nova Londrina","Rosana (São Paulo)","São Pedro do Paraná"] },
{ name:"Mariluz", borderingCities: ["Alto Piquiri","Cruzeiro do Oeste","Formosa do Oeste","Goioerê","Moreira Sales","Perobal","Umuarama"] },
{ name:"Maringá", borderingCities: ["Ângulo","Astorga","Floresta","Iguaraçu","Mandaguaçu","Marialva","Paiçandu","Sarandi"] },
{ name:"Mariópolis", borderingCities: ["Clevelândia","Galvão (SC)","Jupiá (SC)","Pato Branco","São Domingos (SC)","Vitorino"] },
{ name:"Maripá", borderingCities: ["Assis Chateaubriand","Nova Santa Rosa","Palotina","Toledo"] },
{ name:"Marmeleiro", borderingCities: ["Campo Erê(SC)","Flor da Serra do Sul","Francisco Beltrão","Palma Sola(SC)","Renascença"] },
{ name:"Marquinho", borderingCities: ["Cantagalo","Goioxim","Laranjeiras do Sul","Nova Laranjeiras","Palmital"] },
{ name:"Marumbi", borderingCities: ["Bom Sucesso","Cambira","Jandaia do Sul","Kaloré","Novo Itacolomi","São Pedro do Ivaí"] },
{ name:"Matelândia", borderingCities: ["Capanema","Céu Azul","Diamante d'Oeste","Medianeira","Ramilândia","Serranópolis do Iguaçu","Vera Cruz do Oeste"] },
{ name:"Matinhos", borderingCities: ["Guaratuba","Paranaguá","Pontal do Paraná"] },
{ name:"Mato Rico", borderingCities: ["Palmital","Pitanga","Roncador"] },
{ name:"Mauá da Serra", borderingCities: ["Faxinal","Marilândia do Sul","Ortigueira","Tamarana"] },
{ name:"Medianeira", borderingCities: ["Itaipulândia","Matelândia","Missal","Ramilândia","São Miguel do Iguaçu","Serranópolis do Iguaçu"] },
{ name:"Mercedes", borderingCities: ["Guaíra","Marechal Cândido Rondon","Nova Santa Rosa","Terra Roxa"] },
{ name:"Mirador", borderingCities: ["Amaporã","Guaporema","Nova Aliança do Ivaí","Paraíso do Norte","Paranavaí"] },
{ name:"Miraselva", borderingCities: ["Centenário do Sul","Florestópolis","Jaguapitã","Prado Ferreira"] },
{ name:"Missal", borderingCities: ["Diamante d'Oeste","Itaipulândia","Medianeira","Ramilândia","Santa Helena"] },
{ name:"Moreira Sales", borderingCities: ["Cruzeiro do Oeste","Goioerê","Janiópolis","Mariluz","Tuneiras do Oeste"] },
{ name:"Morretes", borderingCities: ["Antonina","Campina Grande do Sul","Guaratuba","Paranaguá","Piraquara","Quatro Barras","São José dos Pinhais"] },
{ name:"Munhoz de Melo", borderingCities: ["Astorga","Iguaraçu","Jaguapitã","Santa Fé"] },
{ name:"Nossa Senhora das Graças", borderingCities: ["Cafeara","Colorado","Guaraci","Santa Fé","Santo Inácio"] },
{ name:"Nova Aliança do Ivaí", borderingCities: ["Mirador","Paraíso do Norte","Paranavaí","Tamboara"] },
{ name:"Nova América da Colina", borderingCities: ["Assaí","Cornélio Procópio","Nova Fátima","São Sebastião da Amoreira","Uraí"] },
{ name:"Nova Aurora", borderingCities: ["Assis Chateaubriand","Cafelândia","Corbélia","Formosa do Oeste","Iracema do Oeste","Jesuítas","Quarto Centenário","Tupãssi","Ubiratã"] },
{ name:"Nova Cantu", borderingCities: ["Altamira do Paraná","Campina da Lagoa","Laranjal","Mamborê","Palmital","Roncador"] },
{ name:"Nova Esperança", borderingCities: ["Alto Paraná","Atalaia","Cruzeiro do Sul","Floraí","Presidente Castelo Branco","Tamboara","Uniflor"] },
{ name:"Nova Esperança do Sudoeste", borderingCities: ["Ampére","Enéas Marques","Francisco Beltrão","Salto do Lontra","Santa Izabel do Oeste"] },
{ name:"Nova Fátima", borderingCities: ["Congonhinhas","Cornélio Procópio","Nova América da Colina","Ribeirão do Pinhal","Santo Antônio do Paraíso","São Sebastião da Amoreira"] },
{ name:"Nova Laranjeiras", borderingCities: ["Diamante do Sul","Espigão Alto do Iguaçu","Guaraniaçu","Laranjal","Laranjeiras do Sul","Marquinho","Palmital","Rio Bonito do Iguaçu"] },
{ name:"Nova Londrina", borderingCities: ["Diamante do Norte","Guairaçá","Itaúna do Sul","Loanda","Marilena","Rosana(SP)"] },
{ name:"Nova Olímpia", borderingCities: ["Cidade Gaúcha","Cruzeiro do Oeste","Maria Helena","Tapejara","Tapira"] },
{ name:"Nova Prata do Iguaçu", borderingCities: ["Boa Esperança do Iguaçu","Boa Vista da Aparecida","Capitão Leônidas Marques","Realeza","Salto do Lontra","Santa Izabel do Oeste","Três Barras do Paraná"] },
{ name:"Nova Santa Bárbara", borderingCities: ["Santa Cecília do Pavão","Santo Antônio do Paraíso","São Jerônimo da Serra"] },
{ name:"Nova Santa Rosa", borderingCities: ["Marechal Cândido Rondon","Maripá","Mercedes","Palotina","Quatro Pontes","Terra Roxa","Toledo"] },
{ name:"Nova Tebas", borderingCities: ["Arapuã","Iretama","Jardim Alegre","Manoel Ribas","Pitanga","Roncador"] },
{ name:"Novo Itacolomi", borderingCities: ["Apucarana","Borrazópolis","Cambira","Kaloré","Marumbi","Rio Bom"] },
{ name:"Ortigueira", borderingCities: ["Curiúva","Faxinal","Grandes Rios","Imbaú","Mauá da Serra","Reserva","Rosário do Ivaí","São Jerônimo da Serra","Sapopema","Tamarana","Telêmaco Borba"] },
{ name:"Ourizona", borderingCities: ["Doutor Camargo","Mandaguaçu","Paiçandu","São Jorge do Ivaí","Terra Boa"] },
{ name:"Ouro Verde do Oeste", borderingCities: ["Marechal Cândido Rondon","São José das Palmeiras","São Pedro do Iguaçu","Toledo"] },
{ name:"Paiçandu", borderingCities: ["Doutor Camargo","Mandaguaçu","Maringá","Ourizona"] },
{ name:"Palmas", borderingCities: ["Abelardo Luz (SC)","Água Doce (SC)","Bituruna","Clevelândia","Coronel Domingos Soares","General Carneiro","Passos Maia(SC)"] },
{ name:"Palmeira", borderingCities: ["Balsa Nova","Campo Largo","Lapa","Ponta Grossa","Porto Amazonas","São João do Triunfo","Teixeira Soares"] },
{ name:"Palmital", borderingCities: ["Goioxim","Laranjal","Marquinho","Mato Rico","Nova Cantu","Nova Laranjeiras","Pitanga","Roncador","Santa Maria do Oeste"] },
{ name:"Palotina", borderingCities: ["Assis Chateaubriand","Francisco Alves","Iporã","Maripá","Nova Santa Rosa","Terra Roxa"] },
{ name:"Paraíso do Norte", borderingCities: ["Guaporema","Mirador","Nova Aliança do Ivaí","Rondon","São Carlos do Ivaí","São Manoel do Paraná","Tamboara"] },
{ name:"Paranacity", borderingCities: ["Colorado","Cruzeiro do Sul","Inajá","Lobato","Paranapoema","São João do Caiuá"] },
{ name:"Paranaguá", borderingCities: ["Antonina","Guaraqueçaba","Guaratuba","Matinhos.","Morretes","Pontal do Paraná"] },
{ name:"Paranapoema", borderingCities: ["Colorado","Inajá","Itaguajé","Jardim Olinda","Paranacity","Teodoro Sampaio(SP)"] },
{ name:"Paranavaí", borderingCities: ["Alto Paraná","Amaporã","Euclides da Cunha Paulista(SP)","Guairaçá","Mirador","Nova Aliança do Ivaí","Santo Antônio do Caiuá","São João do Caiuá","Tamboara","Teodoro Sampaio(SP)","Terra Rica"] },
{ name:"Pato Bragado", borderingCities: ["Entre Rios do Oeste","Marechal Cândido Rondon"] },
{ name:"Pato Branco", borderingCities: ["Bom Sucesso do Sul","Clevelândia","Coronel Vivida","Honório Serpa","Itapejara d'Oeste","Mariópolis","Vitorino"] },
{ name:"Paula Freitas", borderingCities: ["Canoinhas(SC)","Irineópolis(SC)","Paulo Frontin","Porto União(SC)","União da Vitória"] },
{ name:"Paulo Frontin", borderingCities: ["Canoinhas (SC)","Mallet","Paula Freitas","São Mateus do Sul"] },
{ name:"Peabiru", borderingCities: ["Araruna","Barbosa Ferraz","Campo Mourão","Corumbataí do Sul","Engenheiro Beltrão","Fênix","Quinta do Sol","Terra Boa"] },
{ name:"Perobal", borderingCities: ["Alto Piquiri","Cafezal do Sul","Mariluz","Umuarama"] },
{ name:"Pérola", borderingCities: ["Altônia","Cafezal do Sul","Esperança Nova","Iporã","São Jorge do Patrocínio","Xambrê"] },
{ name:"Pérola d'Oeste", borderingCities: ["Bela Vista da Caroba","Planato","Pranchita"] },
{ name:"Piên", borderingCities: ["Agudos do Sul","Campo Alegre (SC)","Campo do Tenente","Quitandinha","Rio Negro","São Bento do Sul(SC)"] },
{ name:"Pinhais", borderingCities: ["Colombo","Curitiba","Piraquara","Quatro Barras","São José dos Pinhais"] },
{ name:"Pinhal de São Bento", borderingCities: ["Ampére","Francisco Beltrão","Manfrinópolis","Salgado Filho","Santo Antônio do Sudoeste"] },
{ name:"Pinhalão", borderingCities: ["Arapoti","Ibaiti","Jaboti","Japira","Tomazina"] },
{ name:"Pinhão", borderingCities: ["Bituruna","Candói","Coronel Domingos Soares","Cruz Machado","Foz do Jordão","Guarapuava","Inácio Martins","Reserva do Iguaçu"] },
{ name:"Piraí do Sul", borderingCities: ["Arapoti","Castro","Doutor Ulysses","Jaguariaíva","Tibagi","Ventania"] },
{ name:"Piraquara", borderingCities: ["Morretes","Pinhais","Quatro Barras","São José dos Pinhais"] },
{ name:"Pitanga", borderingCities: ["Boa Ventura de São Roque","Cândido de Abreu","Manoel Ribas","Mato Rico","Nova Tebas","Palmital","Roncador","Santa Maria do Oeste"] },
{ name:"Pitangueiras", borderingCities: ["Astorga","Jaguapitã","Rolândia","Sabáudia"] },
{ name:"Planaltina do Paraná", borderingCities: ["Amaporã","Cidade Gaúcha","Guairaçá","Loanda","Santa Mônica","Tapira"] },
{ name:"Planalto", borderingCities: ["Ampére","Capanema","Pérola d'Oeste","Realeza"] },
{ name:"Ponta Grossa", borderingCities: ["Campo Largo","Carambeí","Castro","Ipiranga","Palmeira","Teixeira Soares","Tibagi"] },
{ name:"Pontal do Paraná", borderingCities: ["Matinhos","Paranaguá"] },
{ name:"Porecatu", borderingCities: ["Alvorada do Sul","Centenário do Sul","Florestópolis","Narandiba(SP)","Taciba(SP)"] },
{ name:"Porto Amazonas", borderingCities: ["Balsa Nova","Lapa","Palmeira"] },
{ name:"Porto Barreiro", borderingCities: ["Candói","Chopinzinho","Laranjeiras do Sul","Rio Bonito do Iguaçu","Virmond"] },
{ name:"Porto Rico", borderingCities: ["Batayporã(MS)","Loanda","Querência do Norte","Santa Cruz de Monte Castelo","São Pedro do Paraná","Taquarussu (MS)"] },
{ name:"Porto Vitória", borderingCities: ["Bituruna","General Carneiro","Porto União(SC)","União da Vitória"] },
{ name:"Prado Ferreira", borderingCities: ["Bela Vista do Paraíso","Cambé","Florestópolis","Jaguapitã","Miraselva"] },
{ name:"Pranchita", borderingCities: ["Ampére","Bela Vista da Caroba","Pérola d'Oeste","Santo Antônio do Sudoeste"] },
{ name:"Presidente Castelo Branco", borderingCities: ["Atalaia","Floraí","Mandaguaçu","Nova Esperança","São Jorge do Ivaí"] },
{ name:"Primeiro de Maio", borderingCities: ["Alvorada do Sul","Bela Vista do Paraíso","Iepê (SP)","Sertaneja","Sertanópolis"] },
{ name:"Prudentópolis", borderingCities: ["Cândido de Abreu","Guamiranga","Guarapuava","Imbituva","Irati","Ivaí","Turvo"] },
{ name:"Quarto Centenário", borderingCities: ["Formosa do Oeste","Goioerê","Nova Aurora","Rancho Alegre d'Oeste","Ubiratã"] },
{ name:"Quatiguá", borderingCities: ["Guapirama","Joaquim Távora","Siqueira Campos","Tomazina"] },
{ name:"Quatro Barras", borderingCities: ["Campina Grande do Sul","Colombo","Morretes","Pinhais","Piraquara"] },
{ name:"Quatro Pontes", borderingCities: ["Marechal Cândido Rondon","Nova Santa Rosa","Toledo"] },
{ name:"Quedas do Iguaçu", borderingCities: ["Catanduvas","Cruzeiro do Iguaçu","Espigão Alto do Iguaçu","Guaraniaçu","Rio Bonito do Iguaçu","São João","São Jorge d'Oeste","Três Barras do Paraná"] },
{ name:"Querência do Norte", borderingCities: ["Icaraíma","Ivaté","Naviraí(MS)","Porto Rico","Santa Cruz de Monte Castelo","Taquarussu(MS)"] },
{ name:"Quinta do Sol", borderingCities: ["Engenheiro Beltrão","Fênix","Itambé","Peabiru"] },
{ name:"Quitandinha", borderingCities: ["Agudos do Sul","Campo do Tenente","Contenda","Lapa","Mandirituba","Piên"] },
{ name:"Ramilândia", borderingCities: ["Diamante d'Oeste","Matelândia","Medianeira","Missal"] },
{ name:"Rancho Alegre", borderingCities: ["Ibiporã","Jataizinho","Sertaneja","Sertanópolis","Uraí"] },
{ name:"Rancho Alegre D'Oeste", borderingCities: ["Goioerê","Janiópolis","Juranda","Quarto Centenário","Ubiratã"] },
{ name:"Realeza", borderingCities: ["Ampére","Capanema","Capitão Leônidas Marques","Nova Prata do Iguaçu","Planalto","Santa Izabel do Oeste"] },
{ name:"Rebouças", borderingCities: ["Fernandes Pinheiro","Irati","Rio Azul","São João do Triunfo","São Mateus do Sul"] },
{ name:"Renascença", borderingCities: ["Bom Sucesso do Sul","Campo Erê(SC)","Francisco Beltrão","Marmeleiro","São Lourenço do Oeste(SC)","Vitorino"] },
{ name:"Reserva", borderingCities: ["Cândido de Abreu","Imbaú","Ivaí","Ortigueira","Rosário do Ivaí","Tibagi"] },
{ name:"Reserva do Iguaçu", borderingCities: ["Coronel Domingos Soares","Foz do Jordão","Mangueirinha","Pinhão"] },
{ name:"Ribeirão Claro", borderingCities: ["Carlópolis","Chavantes(SP)","Fartura(SP)","Jacarezinho","Joaquim Távora","Timburi(SP)"] },
{ name:"Ribeirão do Pinhal", borderingCities: ["Abatiá","Congonhinhas","Cornélio Procópio","Ibaiti","Jundiaí do Sul","Nova Fátima"] },
{ name:"Rio Azul", borderingCities: ["Cruz Machado","Inácio Martins","Irati","Mallet","Rebouças","São Mateus do Sul"] },
{ name:"Rio Bom", borderingCities: ["Apucarana","Borrazópolis","Faxinal","Marilândia do Sul","Novo Itacolomi"] },
{ name:"Rio Bonito do Iguaçu", borderingCities: ["Chopinzinho","Espigão Alto do Iguaçu","Laranjeiras do Sul","Nova Laranjeiras","Porto Barreiro","Quedas do Iguaçu","São João","Saudade do Iguaçu","Sulina"] },
{ name:"Rio Branco do Ivaí", borderingCities: ["Ariranha do Ivaí","Cândido de Abreu","Grandes Rios","Ivaiporã","Rosário do Ivaí"] },
{ name:"Rio Branco do Sul", borderingCities: ["Almirante Tamandaré","Bocaiúva do Sul","Castro","Cerro Azul","Colombo","Itaperuçu"] },
{ name:"Rio Negro", borderingCities: ["Campo do Tenente","Lapa","Mafra (SC)","Piên","Rio Negrinho (SC)"] },
{ name:"Rolândia", borderingCities: ["Arapongas","Cambé","Jaguapitã","Pitangueiras","Sabáudia"] },
{ name:"Roncador", borderingCities: ["Iretama","Luiziana","Mato Rico","Nova Cantu","Nova Tebas","Palmital","Pitanga"] },
{ name:"Rondon", borderingCities: ["Cidade Gaúcha","Guaporema","Indianópolis","Paraíso do Norte","São Manoel do Paraná","Tapejara"] },
{ name:"Rosário do Ivaí", borderingCities: ["Cândido de Abreu","Grandes Rios","Ortigueira","Reserva","Rio Branco do Ivaí"] },
{ name:"Sabáudia", borderingCities: ["Apucarana","Arapongas","Astorga","Mandaguari","Pitangueiras","Rolândia"] },
{ name:"Salgado Filho", borderingCities: ["Bom Jesus do Sul","Flor da Serra do Sul","Manfrinópolis","Pinhal de São Bento","Santo Antônio do Sudoeste"] },
{ name:"Salto do Itararé", borderingCities: ["Barão de Antonina(SP)","Carlópolis","Santana do Itararé","Siqueira Campos"] },
{ name:"Salto do Lontra", borderingCities: ["Boa Esperança do Iguaçu","Dois Vizinhos","Enéas Marques","Nova Esperança do Sudoeste","Nova Prata do Iguaçu","Santa Isabel do Oeste"] },
{ name:"Santa Amélia", borderingCities: ["Abatiá","Bandeirantes","Cornélio Procópio","Ribeirão do Pinhal"] },
{ name:"Santa Cecília do Pavão", borderingCities: ["Assaí","Nova Santa Bárbara","Santo Antônio do Paraíso","São Jerônimo da Serra","São Sebastião da Amoreira"] },
{ name:"Santa Cruz de Monte Castelo", borderingCities: ["Douradina","Ivaté","Loanda","Porto Rico","Querência do Norte","Santa Isabel do Ivaí"] },
{ name:"Santa Fé", borderingCities: ["Ângulo","Colorado","Flórida","Guaraci","Iguaraçu","Jaguapitã","Lobato","Munhoz de Melo","Nossa Senhora das Graças"] },
{ name:"Santa Helena", borderingCities: ["Diamante d'Oeste","Entre Rios do Oeste","Itaipulândia","Missal","São José das Palmeiras"] },
{ name:"Santa Inês", borderingCities: ["Colorado","Itaguajé","Pirapozinho (SP)","Sandovalina (SP)","Santo Inácio"] },
{ name:"Santa Isabel do Ivaí", borderingCities: ["Douradina","Loanda","Santa Cruz de Monte Castelo","Santa Mônica","Tapira"] },
{ name:"Santa Izabel do Oeste", borderingCities: ["Ampére","Nova Esperança do Sudoeste","Nova Prata do Iguaçu","Realeza","Salto do Lontra"] },
{ name:"Santa Lúcia", borderingCities: ["Boa Vista da Aparecida","Capitão Leônidas Marques","Lindoeste"] },
{ name:"Santa Maria do Oeste", borderingCities: ["Boa Ventura de São Roque","Campina do Simão","Goioxim","Palmital","Pitanga","Turvo"] },
{ name:"Santa Mariana", borderingCities: ["Bandeirantes","Cândido Mota(SP)","Cornélio Procópio","Florínea (SP)","Itambaracá","Leópolis"] },
{ name:"Santa Mônica", borderingCities: ["Loanda","Planaltina do Paraná","Santa Isabel do Ivaí","Tapira"] },
{ name:"Santa Tereza do Oeste", borderingCities: ["Cascavel","Céu Azul","Lindoeste","São Pedro do Iguaçu","Toledo"] },
{ name:"Santa Terezinha de Itaipu", borderingCities: ["Foz do Iguaçu","São Miguel do Iguaçu"] },
{ name:"Santana do Itararé", borderingCities: ["Barão de Antonina(SP)","Itaporanga (SP)","Riversul (SP)","Salto do Itararé","São José da Boa Vista","Siqueira Campos","Venceslau Brás"] },
{ name:"Santo Antônio da Platina", borderingCities: ["Abatiá","Bandeirantes","Barra do Jacaré","Guapirama","Jacarezinho","Joaquim Távora","Jundiaí do Sul"] },
{ name:"Santo Antônio do Caiuá", borderingCities: ["Inajá","Paranavaí","São João do Caiuá","Teodoro Sampaio (SP)"] },
{ name:"Santo Antônio do Paraíso", borderingCities: ["Congonhinhas.","Nova Fátima","Nova Santa Bárbara","Santa Cecília do Pavão","São Jerônimo da Serra","São Sebastião da Amoreira"] },
{ name:"Santo Antônio do Sudoeste", borderingCities: ["Ampére","Bom Jesus do Sul","Pinhal de São Bento","Pranchita","Salgado Filho"] },
{ name:"Santo Inácio", borderingCities: ["Cafeara","Colorado","Lupionópolis","Nossa Senhora das Graças","Pirarapozinho(SP)","Santa Inês"] },
{ name:"São Carlos do Ivaí", borderingCities: ["Floraí","Japurá","Paraíso do Norte","São Jorge do Ivaí","São Manoel do Paraná","São Tomé","Tamboara"] },
{ name:"São Jerônimo da Serra", borderingCities: ["Assaí","Congonhinhas","Londrina","Nova Santa Bárbara","Ortigueira","Santa Cecília do Pavão","Santo Antônio do Paraíso","Sapopema","Tamarana"] },
{ name:"São João", borderingCities: ["Chopinzinho","Coronel Vivida","Itapejara d'Oeste","Quedas do Iguaçu","São Jorge d'Oeste","Sulina","Verê"] },
{ name:"São João do Caiuá", borderingCities: ["Alto Paraná","Cruzeiro do Sul","Inajá","Paranacity","Paranavaí","Santo Antônio do Caiuá"] },
{ name:"São João do Ivaí", borderingCities: ["Barbosa Ferraz","Borrazópolis","Fênix","Godoy Moreira","Kaloré","Lunardelli","São Pedro do Ivaí"] },
{ name:"São João do Triunfo", borderingCities: ["Antônio Olinto","Fernandes Pinheiro","Lapa","Palmeira","Rebouças","São Mateus do Sul"] },
{ name:"São Jorge do Ivaí", borderingCities: ["Floraí","Jussara","Ourizona","Presidente Castelo Branco","São Carlos do Ivaí","São Tomé","Terra Boa"] },
{ name:"São Jorge do Patrocínio", borderingCities: ["Alto Paraíso","Altônia","Eldorado(MS)","Esperança Nova","Itaiquiraí(MS)","Pérola"] },
{ name:"São Jorge d'Oeste", borderingCities: ["Cruzeiro do Iguaçu","Dois Vizinhos","Quedas do Iguaçu","São João","Verê"] },
{ name:"São José da Boa Vista", borderingCities: ["Arapoti","Jaguariaíva","Riversul(SP)","Santana do Itararé","Sengés","Wenceslau Braz"] },
{ name:"São José das Palmeiras", borderingCities: ["Diamante d'Oeste","Entre Rios do Oeste","Marechal Cândido Rondon","Ouro Verde do Oeste","Santa Helena","São Pedro do Iguaçu"] },
{ name:"São José dos Pinhais", borderingCities: ["Curitiba","Fazenda Rio Grande","Guaratuba","Mandirituba","Morretes","Pinhais","Piraquara","Tijucas do Sul"] },
{ name:"São Manoel do Paraná", borderingCities: ["Indianópolis","Japurá","Paraíso do Norte","Rondon","São Carlos do Ivaí"] },
{ name:"São Mateus do Sul", borderingCities: ["Antônio Olinto","Canoinhas(SC)","Mallet","Paulo Frontin","Rebouças","Rio Azul","São João do Triunfo","Três Barras(SC)"] },
{ name:"São Miguel do Iguaçu", borderingCities: ["Foz do Iguaçu","Itaipulândia","Medianeira","Santa Terezinha de Itaipu","Serranópolis do Iguaçu"] },
{ name:"São Pedro do Iguaçu", borderingCities: ["Céu Azul","Diamante do Oeste","Ouro Verde do Oeste","Santa Tereza do Oeste","São José das Palmeiras","Toledo","Vera Cruz do Oeste"] },
{ name:"São Pedro do Ivaí", borderingCities: ["Bom Sucesso","Fênix","Itambé","Kaloré","Marumbi","São João do Ivaí"] },
{ name:"São Pedro do Paraná", borderingCities: ["Batayporã(MS)","Loanda","Marilena","Porto Rico"] },
{ name:"São Sebastião da Amoreira", borderingCities: ["Assaí","Nova América da Colina","Nova Fátima","Santa Cecília do Pavão","Santo Antônio do Paraíso"] },
{ name:"São Tomé", borderingCities: ["Cianorte","Indianópolis","Japurá","Jussara","São Carlos do Ivaí","São Jorge do Ivaí"] },
{ name:"Sapopema", borderingCities: ["Congonhinhas","Curiúva","Figueira","Ortigueira","São Jerônimo da Serra"] },
{ name:"Sarandi", borderingCities: ["Marialva","Maringá"] },
{ name:"Saudade do Iguaçu", borderingCities: ["Chopinzinho","Rio Bonito do Iguaçu","Sulina"] },
{ name:"Sengés", borderingCities: ["Bom Sucesso de Itararé (SP)","Doutor Ulysses","Itararé (SP)","Jaguariaíva","Riversul(SP)","São José da Boa Vista"] },
{ name:"Serranópolis do Iguaçu", borderingCities: ["Capanema","Matelândia","Medianeira","São Miguel do Iguaçu"] },
{ name:"Sertaneja", borderingCities: ["Florínea(SP)","Iepê(SP)","Leópolis","Macaraí(SP)","Pedrinhas Paulista(SP)","Primeiro de Maio","Rancho Alegre","Sertanópolis","Uraí"] },
{ name:"Sertanópolis", borderingCities: ["Bela Vista do Paraíso","Cambé","Ibiporã","Londrina","Primeiro de Maio","Rancho Alegre","Sertaneja"] },
{ name:"Siqueira Campos", borderingCities: ["Carlópolis","Joaquim Távora","Quatiguá","Salto do Itararé","Santana do Itararé","Tomazina","Wenceslau Braz"] },
{ name:"Sulina", borderingCities: ["Chopinzinho","Rio Bonito do Iguaçu","São João","Saudade do Iguaçu"] },
{ name:"Tamarana", borderingCities: ["Londrina","Marilândia do Sul","Mauá da Serra","Ortigueira","São Jerônimo da Serra"] },
{ name:"Tamboara", borderingCities: ["Alto Paraná","Floraí","Nova Aliança do Ivaí","Nova Esperança","Paraíso do Norte","Paranavaí","São Carlos do Ivaí"] },
{ name:"Tapejara", borderingCities: ["Cianorte","Cidade Gaúcha","Cruzeiro do Oeste","Indianópolis","Nova Olímpia","Rondon","Tuneiras do Oeste"] },
{ name:"Tapira", borderingCities: ["Cidade Gaúcha","Douradina","Maria Helena","Nova Olímpia","Planaltina do Paraná","Santa Isabel do Ivaí","Santa Mônica"] },
{ name:"Teixeira Soares", borderingCities: ["Fernandes Pinheiro","Imbituva","Ipiranga","Palmeira","Ponta Grossa"] },
{ name:"Telêmaco Borba", borderingCities: ["Curiúva","Imbaú","Ortigueira","Tibagi","Ventania"] },
{ name:"Terra Boa", borderingCities: ["Araruna","Doutor Camargo","Engenheiro Beltrão","Ivatuba","Jussara","Ourizona","Peabiru","São Jorge do Ivaí"] },
{ name:"Terra Rica", borderingCities: ["Diamante do Norte","Euclides da Cunha Paulista(SP)","Guairaçá","Itaúna do Sul","Paranavaí","Teodoro Sampaio (SP)"] },
{ name:"Terra Roxa", borderingCities: ["Altônia","Francisco Alves","Guaíra","Iporã","Mercedes","Nova Santa Rosa","Palotina"] },
{ name:"Tibagi", borderingCities: ["Carambeí","Castro","Imbaú","Ipiranga","Ivaí","Piraí do Sul","Ponta Grossa","Reserva","Telêmaco Borba","Ventania"] },
{ name:"Tijucas do Sul", borderingCities: ["Agudos do Sul","Campo Alegre(SC)","Guaratuba","Mandirituba","São José dos Pinhais"] },
{ name:"Toledo", borderingCities: ["Assis Chateaubriand","Cascavel","Marechal Cândido Rondon","Maripá","Nova Santa Rosa","Ouro Verde do Oeste","Quatro Pontes","Santa Tereza do Oeste","São Pedro do Iguaçu","Tupãssi"] },
{ name:"Tomazina", borderingCities: ["Arapoti","Conselheiro Mairinck","Guapirama","Jaboti","Pinhalão","Quatiguá","Siqueira Campos","Wenceslau Braz"] },
{ name:"Três Barras do Paraná", borderingCities: ["Boa Esperança do Iguaçu","Boa Vista da Aparecida","Cascavel","Catanduvas","Cruzeiro do Iguaçu","Nova Prata do Iguaçu","Quedas do Iguaçu"] },
{ name:"Tunas do Paraná", borderingCities: ["Adrianópolis","Bocaiúva do Sul","Cerro Azul"] },
{ name:"Tuneiras do Oeste", borderingCities: ["Araruna","Cianorte","Cruzeiro do Oeste","Farol","Janiópolis","Moreira Sales","Tapejara"] },
{ name:"Tupãssi", borderingCities: ["Assis Chateaubriand","Cafelândia","Cascavel","Nova Aurora","Toledo"] },
{ name:"Turvo", borderingCities: ["Boa Ventura de São Roque","Campina do Simão","Cândido de Abreu","Guarapuava","Prudentópolis","Santa Maria do Oeste"] },
{ name:"Ubiratã", borderingCities: ["Anahy","Braganey","Campina da Lagoa","Corbélia","Iguatu","Juranda","Nova Aurora","Quarto Centenário","Rancho Alegre d'Oeste"] },
{ name:"Umuarama", borderingCities: ["Alto Paraíso","Cafezal do Sul","Cruzeiro do Oeste","Douradina","Icaraíma","Ivaté","Maria Helena","Mariluz","Perobal","Xambrê"] },
{ name:"União da Vitória", borderingCities: ["Bituruna","Cruz Machado","Mallet","Paula Freitas","Paulo Frontin","Porto União (SC)","Porto Vitória"] },
{ name:"Uniflor", borderingCities: ["Atalaia","Cruzeiro do Sul","Lobato","Nova Esperança"] },
{ name:"Uraí", borderingCities: ["Assaí","Cornélio Procópio","Jataizinho","Leópolis","Nova América da Colina","Rancho Alegre","Sertaneja"] },
{ name:"Ventania", borderingCities: ["Arapoti","Curiúva","Ibaiti","Piraí do Sul","Telêmaco Borba","Tibagi"] },
{ name:"Vera Cruz do Oeste", borderingCities: ["Céu Azul","Diamante d'Oeste","Matelândia","São Pedro do Iguaçu"] },
{ name:"Verê", borderingCities: ["Dois Vizinhos","Enéas Marques","Francisco Beltrão","Itapejara d'Oeste","São João","São Jorge d'Oeste"] },
{ name:"Virmond", borderingCities: ["Candói","Cantagalo","Laranjeiras do Sul","Porto Barreiro"] },
{ name:"Vitorino", borderingCities: ["Bom Sucesso do Sul","Jupiá(SC)","Mariópolis","Pato Branco","Renascença","São Lourenço do Oeste(SC)"] },
{ name:"Wenceslau Braz", borderingCities: ["Arapoti","Santana do Itararé","São José da Boa Vista","Siqueira Campos","Tomazina"] },
{ name:"Xambrê", borderingCities: ["Alto Paraíso","Cafezal do Sul","Esperança Nova","Pérola","Umuarama"] }


  ];

  const select = document.createElement('select');
  select.id = 'citySelect';

  // Create default option
  const defaultOption = document.createElement('option');
  defaultOption.value = '';
  defaultOption.textContent = 'Selecione um município';
  select.appendChild(defaultOption);

  // Create options for each city
  cities.forEach((city, index) => {
    const option = document.createElement('option');
    option.value = index;
    option.textContent = city.name;
    select.appendChild(option);
  });

  // Create a container for bordering cities
  const borderingCitiesContainer = document.createElement('div');
  borderingCitiesContainer.id = 'borderingCitiesContainer';
  
  // Append select box
  container.appendChild(select);
  
  // Insert two line breaks after the selection box
  const br1 = document.createElement('br');
  const br2 = document.createElement('br');
  container.appendChild(br1);
  container.appendChild(br2);
  
  container.appendChild(borderingCitiesContainer);

  // Event listener to display bordering cities
  select.addEventListener('change', function () {
    borderingCitiesContainer.innerHTML = '';  // Clear previous content

    if (select.value !== '') {
      const selectedCity = cities[select.value];

      // Create and append title
      const title = document.createElement('p');
      title.textContent = `Municípios limítrofes de ${selectedCity.name}:`;
      borderingCitiesContainer.appendChild(title);

      // Add a line break after the title
      const lineBreak = document.createElement('br');
      borderingCitiesContainer.appendChild(lineBreak);

      // Append each city in a separate div (without list markers)
      selectedCity.borderingCities.forEach(city => {
        const cityDiv = document.createElement('div');
        cityDiv.textContent = city;
        borderingCitiesContainer.appendChild(cityDiv);
      });
    }
  });
}
